= Базовые объекты

[*bla*]

Модуль "Базовые объекты" добавляет в Систему:

* новые типы карточек: Бизнес-календарь, Группа заданий, Документ, Задание, Карточка подразделения, Карточка подразделения контрагента, Карточка сервера, Карточка сотрудника, Карточка сотрудника контрагента, Карточка строки справочника, Маршрут согласования, Расширение навигатора, Согласование, Список категорий, Список опросов, Список подписей, Список ссылок на карточки, Список ссылок на карточки версионного файла, Список ссылок на карточки заданий, Ход согласований, Этап согласования;
* новые типы справочников: Справочник видов карточек, Справочник категорий, Справочник контрагентов, Справочник меток подписей, Справочник серверов, Справочник сотрудников и Справочник ссылок;
* конструкторы: Конструктор правил нумерации, Конструктор разметок, Конструктор ролей, Конструктор скриптов, Конструктор состояний, Конструктор справочников;
* поддержку ролевой модели безопасности.

Также модуль "Базовые объекты" предоставляет функции, позволяющие выполнять порученные задания с помощью почтового клиента.