= Перечень эксплуатационной документации

Каждый модуль {dv} сопровождается комплектом технической документации. Данный комплект может включать следующие документы:

* "Руководство администратора" – содержит программные и аппаратные требования модуля, инструкцию по установке и первоначальной настройке, требования к лицензии {dv}. В зависимости от способа разграничения прав пользователей при работе с модулем, документ также может содержать инструкцию по настройке системы {dv} с помощью функций модуля и другую информацию.
* "Руководство пользователя" – содержит инструкцию по работе с функциями модуля, а также может содержать описание основных объектов модуля (карточек) и инструкцию по установке дополнительных компонентов пользовательского уровня.
* "Руководство программиста" – содержит описание программных объектов и функций API модуля, а также инструкцию по разработке компонентов модуля;
* "Описание конструкторов и справочников" – содержит описание пользовательского интерфейса и инструкцию по работе с конструкторами и справочниками, которые добавляются модулем в Систему.
* другие документы и инструкции по модулю.

Также документация ДоксВижн содержит общие документы, относящиеся к нескольким модулям и всей Системе в целом.

Актуальный список документов:

* *Общая документация:*
* "Общее описание системы" – настоящий документ, в котором приведено описание компонентов Системы и взаимосвязей между ними; особенности лицензирования, оказания технической поддержки; перечень эксплуатационной документации.
* "Инструкция по установке системы {dv}" – содержит общие программные и аппаратные требования модулей {dv}, инструкцию по установке базовых модулей {dv} и первоначальной настройке Системы. В данный документ включены отдельные пункты из руководств администратора базовых модулей {dv}. За более подробной инструкцией следует обращаться к руководству администратора соответствующего модуля.
* "Руководство программиста" – содержит описание API, которое предоставляется базовыми модулями {dv}, инструкции и примеры реализации различных компонентов системы {dv}. В данном документе не рассматриваются аспекты разработки, связанные с Web-клиентом – обратитесь к документации модуля "Web-клиент".
* "Руководство по настройке" – содержит полное руководство по настройке поисковых запросов и представлений, информацию по настройке разметок, а также других не системных компонентов {dv}. Отдельные разделы документа отсылают в другим руководствам {dv}, в которых содержится описание требуемой настройки.
* "Описание полей стандартных карточек {dv}" – содержит описание карточек базовых модулей {dv}. Описание включает перечень метаданных с типами и значениями.
* "Инструкция по обновлению {dv} 5.5.X до 5.5.Y" – содержит инструкцию по установке комплекта новых версий модулей {dv}.
* *Документация базовых модулей:*
* Модуль "Платформа":
** "Руководство администратора" – содержит программные и аппаратные требования модуля, инструкцию по установке и настройке сервера {dv}. Также в документе приведена инструкция по управлению базами данных {dv}, настройке внешних файловых хранилищ, полнотекстового поиска и других параметров Системы, приведены рекомендации по обслуживанию.
** "Описание конструкторов и справочников" – содержит описание пользовательского интерфейса и инструкцию по работе со справочниками модуля: "Системные настройки", "Справочник типов папок", "Справочник компонентов".
** "Ограничения на модификацию стандартных настроек модуля" – содержит перечень возможных и запрещенных изменений настроек и объектов модуля.
* Модуль "Базовые объекты":
** "Руководство администратора" – содержит программные и аппаратные требования модуля, инструкцию по установке модуля, настройке маршрутизации заданий в электронную почту. Также в документе приведено описание настроек модуля в справочнике _Системные настройки_.
** "Руководство пользователя" – содержит описание карточки "Бизнес-календарь", инструкцию по выполнению заданий в почтовом клиенте.
** "Описание конструкторов и справочников" – содержит описание пользовательского интерфейса и инструкцию по работе с конструкторами и справочниками модуля: "Конструктор правил нумерации", "Конструктор разметок", "Конструктор ролей", "Конструктор скриптов", "Конструктор состояний", "Конструктор справочников", "Справочник видов карточек", "Справочник категорий", "Справочник контрагентов", "Справочник меток подписей", "Справочник серверов", "Справочник сотрудников", "Справочник ссылок".
** "Ограничения на модификацию стандартных настроек модуля" – содержит перечень возможных и запрещенных изменений настроек и объектов модуля.
* Модуль "Управление процессами":
** "Руководство администратора" – содержит программные и аппаратные требования модуля, инструкцию по установке и настройке модуля. Также в документе содержится описание настроек модуля в "Консоли настройки {dv}" и в справочнике _Системные настройки_, указаны особенности настройки кластера СУБП.
** "Руководство пользователя" – содержит описание Конструктора бизнес-процессов (инструмента для разработки БП); инструкцию по разработке новых бизнес-процессов; описание элементов, используемых при конструировании БП.
* Приложение "Управление документами":
** "Руководство администратора" – содержит требования, инструкцию по установке и настройке приложения, перечислены этапы подготовки приложения к работе с договорами.
** "Руководство пользователя" – содержит описание карточек модуля (*Документ УД*, _Задание УД_ и _Группа заданий УД_); рассмотренные основные примеры работы с документами, заданиями и договорами.
** "Ограничения на модификацию стандартных настроек приложения" – содержит перечень возможных и запрещенных изменений настроек и объектов приложения.
* Модуль "Конструктор согласований":
** "Руководство администратора" – содержит программные и аппаратные требования модуля, инструкцию по установке модуля. Также в документе приведена инструкция по разработке процессов согласования.
** "Руководство пользователя" – содержит инструкцию по выполнению и контролю за выполнением задач согласования: согласование, консолидация и подписание.
** "Ограничения на модификацию стандартных настроек модуля" – содержит перечень возможных и запрещенных изменений настроек и объектов модуля.
* Модуль "Windows-клиент":
** "Руководство администратора" – содержит программные и аппаратные требования модуля, инструкцию по установке, описание административных настроек.
** "Руководство пользователя" – содержит описание пользовательского интерфейса и инструкцию по работе с программами "Windows-клиент" и "Рабочее место администратора".
* Приложение "Делопроизводство 4.5":
** "Руководство администратора" – содержит программные и аппаратные требования приложения, инструкцию по установке приложения "Делопроизводство 4.5", приведено описание настроек приложения в справочнике "Системные настройки".
** "Руководство пользователя" – содержит инструкцию по работе с программой "Личный помощник". Описание карточек библиотеки карточек "Делопроизводство 4.5" и инструкция по работе с карточками приведены в руководстве пользователя системы "{dv} 4.5".