= Управление документами

Приложение "Управление документами" добавляет в Систему готовое к использованию прикладное решение по работе с обычными и договорными документами.

Работу Приложения обеспечивают:

* карточки видов:
* "ДокументУД" с подвидами: "Исходящий", "Заявка", "ОРД", "Рабочий", "Входящий", "Договор", "Акт", "Дополнительное соглашение", "Служебная записка";
* "Файл";
* "Задание УД" с подвидами: "На исполнение", "На ознакомление";
* "Задание КС" с подвидами: "На подписание", "На консолидацию", "Согласование с контрагентом", "Консолидация Договора", "На согласование";
* "Группа заданий УД";
* "Этап согласования", "Маршрут согласования", "Согласование", "Согласование КС";
* "Карточка строки справочника" с подвидом "Группа договоров".
* бизнес-процессы: "УД Отправка почтового уведомления о завершении задания автору", "УД Отправка почтового уведомления о завершении группы заданий автору", "Мониторинг договоров для автоматического продления", "УД Отправка почтового уведомления об отклонении задания автору", "УД Отправка на ознакомление", "КС Основной процесс", "КС Подпроцесс последовательное согласование", "КС Подпроцесс работы с заданиями", "КС Подпроцесс параллельное согласование", "УД Отправка почтового уведомления о начале приемки задания", "УД Отправка почтовых уведомлений", "КС Отзыв или завершение подчиненных заданий","УД Отзыв заданий ГЗ", "КС Процесс приостановки", "КС Процесс запуска после приостановки", "КС Процесс отзыва", "Изменение срока действия Договора при заключении ДС о переносе сроков", "КС Стартовый процесс".

В приложении "Управление документами" реализованы в упрощенном виде основные элементы классического делопроизводства:

* регистрация, хранение и поиск электронных документов;
* классификация документов;
* согласование (в том числе договоров) и подписание документов;
* ознакомление;
* фиксация хода исполнения договоров, в том числе:
* прикрепление рабочих материалов (файлов и карточек);
* прикрепление результатов (консолидированной версии договорного документа, актов, дополнительных соглашений, других дополнительных документов);
* работа с заданиями.