= Безопасность

В {dv} существует три модели безопасности, по которым определяется возможность получения доступа к объекту и возможность выполнения определенных действий с ним: ролевая, дискреционная и мандатная.

Проверка прав на выполнение операции чтение/изменения/удаления объекта включает последовательную проверку прав по мандатной (первая), дискреционной, ролевой (последняя) моделям безопасности. Если по какой-либо модели безопасности операция запрещена, по оставшимся проверка не производится.

Дополнительно:

* Администраторам {dv} всегда предоставляются права на чтение (проверка не выполняется).
* Проверка по ролевой модели безопасности пропускается для объектов, которые не поддерживают ролевую модель (папки), а также карточек, настройки ролевой модели которых не предусматривают возможность запрета.
* Если в ролевой модели есть роли, устанавливающие запрет на операцию, сначала проверяются они. Если ролей, предусматривающих запрет, нет, права вычисляются по первой "разрешающей" роли.

== Ролевая модель безопасности

Ролевая модель безопасности предусматривает разграничение прав доступа к объектам и операциям в зависимости от роли субъекта при работе с объектом. Разграничение прав настраивается с помощью специальной матрицы доступа, содержащей перечень разрешенных и явно запрещенных операций для _роли_ в зависимости от типа операции и состояния объекта. 

_Роль_ субъекта определяется системой {dv} по правилам включения в роль. Правила могут быть настроены с помощью предоставляемых условий или собственных хранимых процедур (SQL). В зависимости от правил, субъект может быть включен в несколько ролей.

Анализ ролевой модели при расчете доступа к конкретной карточке определяется настройками типа карточки, а также наличием или отсутствием в карточке системных данных о ее виде и состоянии (секции `System`).

* При наличии системных данных для анализа используются настройки ролевой модели, определенные для вида. На основании данных настроек формируется дополнительный дескриптор, который объединяется с основным дескриптором карточки.
* Если системные данные в карточке отсутствуют, выполняется поиск "родительской" карточки, для которой определены настройки ролевой модели, и на их основании формируется дескриптор.
* Если будут найдены нескольких родительских карточек с собственными настройками ролевой модели, дополнительный дескриптор будет построен на основании той карточки, которая была получена из базы данных первой.
* Если родительские карточки не найдены, расчет доступа выполняется по собственному дескриптору карточки.

== Дискреционная модель безопасности

В дискреционной модели безопасности управление доступом субъектов к объектам основано на списках управления доступом, в которых для каждой пары субъект – объект установлены допустимые типы доступа (чтение, изменение и т. д.). Каждый объект системы имеет привязанного к нему субъекта, называемого владельцем, и именно владелец устанавливает права доступа к объекту.

Дискреционная безопасность может быть настроена для карточек и справочников, папок, файлов, представлений, поисковых запросов, шаблонов выгрузки данных в Excel.

По умолчанию все пользователи {dv}, включенные в группу безопасности "{dv} Users", получают полные права на все элементы системы.

При проверке прав сотрудника на объект учитываются права данного сотрудника, а также права его непосредственного подразделения/группы/роли. Начиная с {dv} 5.5.2 (версия Платформы) может использоваться альтернативный режим проверки прав, в котором учитываются не только права непосредственной организации/подразделения/группы, но и вышестоящих организаций и групп.

Если права на один объект выданы непосредственно сотруднику и его подразделению/роли/группе, приоритет имеют запрещающие права. Если права перетекают с контейнера объекта (например, карточке с папки), то приоритет имеют права непосредственно выданные на объект.

== Мандатная модель безопасности

Мандатная модель безопасности предусматривает наличие у объектов меток конфиденциальности содержащейся информации (определяют уровень доступа), а у субъектов – допуска к объектам с определенным уровнем метки конфиденциальности.

В системе {dv} имеется пять уровней доступа и допуска: самый низкий, низкий, средний, высокий, самый высокий.

Правила мандатной модели безопасности:

* Субъект имеет право читать и заносить информацию только в документы, уровень доступа которых ниже или равен уровню допуска субъекта.

* Автор документа самостоятельно может изменять уровень доступа к нему на более низкий, чем его уровень допуска.

&gt; Администратор безопасности – пользователь, включенный в группу "{dv} Security Administrators".

* Изменить уровень безопасности как субъекта, так и объекта может только администратор безопасности.

* Пользователи, включенные в группу безопасности "{dv} Administrators" всегда имеют (не может быть изменён) уровень допуска "высокий".

* Пользователи, включенные в группу безопасности "{dv} Security Administrators" всегда имеют (не может быть изменён) уровень допуска "самый высокий".

* Пользователь с любым уровнем допуска создает объекты с уровнем конфиденциальности "самый низкий".

* В папке с любым уровнем доступа вложенная папка и карточка будут созданы с уровнем конфиденциальности "самый низкий".

* Если к карточке с любым уровнем доступа прикладывается файл файловой системы, то создаваемая при этом карточка файла получит уровень конфиденциальности "самый низкий".

* Если к карточке с любым уровнем доступа прикладывается уже существующая карточка файла, то она сохранит свой уровень доступа. Например, пользователь с высоким уровнем допуска может приложить к карточке с низким уровнем доступа файл, имеющий высокий уровень доступа; в этом случае приложенный файл смогут увидеть только те пользователи, которым это позволяет их уровень допуска.

* Карточка, создаваемая из карточки с любым уровнем доступа, будет иметь уровень конфиденциальности "самый низкий".

* Объект унаследует уровень доступа от родительского объекта, если они связаны сильной ссылкой, независимо от уровня конфиденциальности, который был у дочернего объекта.