= Обновление базы данных

При установке новой версии модуля в БД вносятся изменения. Масштаб обновления БД зависит от изменений в схеме карточек относительно текущего состояния в БД:

* если изменилась версия генератора схем карточек – будет выполнено полное обновление БД;
* если изменилась схема библиотеки карточек, но не её карточек – будут установлены/обновлены только расширенные отчёты и скрипты данной библиотеки карточек;
* если изменилась схема карточки в библиотеки карточек – библиотека карточек будет обновлена полностью (будут загружены отчёты и скрипты библиотеки карточек, а также схемы всех карточек);
* если изменений генератора, схемы библиотеки карточек и схем карточек не было – обновление будет выполнено в лёгком режиме. Лёгкий режим обновление подразумевает только обновление версии компонентов библиотеки карточек в БД.

Обновление версии компонентов библиотеки карточек в БД выполняется во всех перечисленных случаях – это требуется для работы механизма автоматического обновления клиентских компонентов в Windows-клиенте.