= Кэширование

В системе {dv} используется многоуровневое кэширование данных сервером и клиентом {dv} ({wincl}).

== Серверный кэш

Кэш параметров пользовательских сессий::
Используется для хранения данных пользовательских сессий, загружаемых из таблицы *dvsys_session* (параметры сессии, наличие лицензии и пр.), а также различных временных вычисляемых объектов. Позволяет снизить нагрузку на БД при получении данных сессии клиента при его обращении к серверу {dv}, а также ускорить восстановление пользовательских сессий после перезапуска сервера {dv}.
+
Размер кэша не ограничен. Периодичность синхронизации кэша с БД регулируется параметром `{hklm-dv}\Platform\5.5\Server\UpdateSessionCacheTimeout` в реестре ОС (по умолчанию -- `3 минуты`). Данные неактивных сессий удаляются из кэша при синхронизации.
+
У кэша есть определённая привязка к БД: первоначально данные кэша синхронизируются с БД по умолчанию, а если сессии в БД нет, проверяются другие подключенные БД.

Кэш информации о пользователях::
Используется для хранения контекста безопасности пользователя: `SID`, `AccountName`, членство в стандартных группах {dv}. Позволяет ускорить выполнение операций проверки членства в группах безопасности {dv}, получения `SID` по `AccountName` и `AccountName` по `SID`.
+
Размер кэша не ограничен. Использование данного кэша регулируется параметром `{hklm-dv}\Platform\5.5\Server\UserInfoCacheMode` (по умолчанию `FALSE` -- отключен).
+
TIP: У кэша отсутствует привязка к БД.

Кэши метаданных::
Используется для хранения XML библиотек карточек и карточек. Позволяет снизить нагрузку при создании новых пользовательских сессий (при загрузке информации о карточках и библиотеках карточек в сессию).
+
Кэши обновляются при запуске сервера, т. к. эти данные, по большей части, неизменны.
+
TIP: Кэш привязан к БД.

Кэши поисков и представлений::
Используется для хранения информации о поисковых запросах и представлениях. Позволяет быстро определить наличие в БД сформированной процедуры поиска или представления. 
+
.Функции кэша управляются параметрами в ветке `{hklm-dv}\Platform\5.5\Server`:
+
* `CacheTreshold` -- определяет количество обращений к элементу (поисковому запросу или представлению), после достижения которого элемент добавляется в кэш (по умолчанию -- `3`).
* `CacheReductionRatio` -- определяет коэффициент, на который будет уменьшен кэш (очищен) при достижении максимального размера.
* `MaxCacheSize` -- максимальное количество элементов в кэше.
+
TIP: Кэш привязан к БД.

Кэш дескрипторов безопасности::
Используется для хранения дескрипторов безопасности. Позволяет снизить нагрузку при проверке прав на объекты по дискреционной модели безопасности.
+
Размер кэша управляется параметром `{hklm-dv}\Platform\5.5\Server\MaxCacheSize` (по умолчанию -- `10000 элементов`).
+
TIP: Кэш привязан к БД.

Кэш файлов::
Используется для хранения данных файлов, хранящихся в {dv}. Позволяет снизить нагрузку на БД при чтении файлов через курсор.
+
.Кэш состоит из двух элементов:
* Папка `%Temp%\Имя-БД`, в которой хранятся файлы, загруженные в кэш.
* Объект в памяти, в котором содержится информация о файлах в кэше.
+
Состояние объекта в кэше проверяется каждый раз при обращении к нему. Проверка происходит по штампу времени, и, если штамп просрочен или отсутствует, файл перезагружается.
+
.Функции кэша управляются параметрами в ветке `{hklm-dv}\Platform\5.5\Server`:
* `FileCacheSize` -- определяет долю диска, которая может использоваться кэшем. Значение задаётся в процентах (по умолчанию -- `10%`). В любом случае занимает не больше места, чем доступно на диске.
* `FileCacheMaxFilesCount` -- определяет максимальное количество файлов в кэше (по умолчанию -- `1000` файлов).
+
TIP: Кэш привязан к БД.

Кэш информации о справочниках::
Используется для хранения служебной информации о справочниках: текущий штамп времени, статус архивирования, описание и прочие. Применяется при формировании сессии, когда клиент требует передачи информации о справочниках.
+
Актуальность данных в кэше проверяется при каждом обращении. Размер кэша не ограничен.
+
TIP: Кэш привязан к БД.

Кэш данных секций справочников::
Используется для хранения данных секций, в которых используется простая модель безопасности. Применяется для быстрого доступа к атрибутивным данным справочников и строк секций справочников.
+
Кэш может содержать дубликаты данных секции, если данные секций загружаются с различными уровнями секций: данные самой секции, секции с подсекциями.
+
Актуальность данных в кэше проверяется при каждом обращении. Размер кэша не ограничен.
+
TIP: Кэш привязан к БД.

Кэш данных карточек::
Используется для хранения XML-описания карточек, служебных атрибутов. Применяется при получении карточек.
+
Для попадания в кэш карточка должна удовлетворять нескольким условиям:
+
* Должна иметь простую модель безопасности.
* Не должна иметь виртуальных полей.
* Поля не должны зависеть от пользователя (флаг `Зависит от пользователя` в схеме).

Кэш информации о файлах::
Используется для хранения служебной информации о файлах. Позволяет снизить нагрузку на БД при запросе информации о файлах.

Кэш курсоров и их страниц::
Используется для хранения курсоров и страниц при чтении данных карточек через курсор. Применяется при получении курсора для чтения карточки.

Кэш результатов поисковых запросов::
Используется для хранения результатов поисковых запросов по секциям карточек. Позволяет снизить нагрузку на БД при выполнении запроса, который выполнялся.

Кэш XSLT-преобразований карточек::
Используется для хранения XSLT-преобразований карточек.

Информация об узлах AlwaysOn::
Используется для хранения списка подключенных реплик, а также выбора реплики AlwaysOn, используемой методами, которые работают с поисками и представлениями.

NOTE: Все перечисленные серверные кэши, кроме файлового, в зависимости от настроек сервера, могут храниться в оперативной памяти или в Redis. Также кэш может быть отключен.

== Серверный кэш расширения Backoffice

Кэш видов, ролей и состояний::
Используется для хранения данных справочников видов, ролей и состояний. Применяется для ускорения работы ролевой модели безопасности.
+
Актуальность данных в кэше проверяется при каждом обращении по штампу времени справочников. Обновляется полностью, если любой из справочников в кэше устарел. 
+
Размер кэша не ограничен.
+
TIP: Кэш привязан к БД.

Кэш ролевой модели::
Используется для хранения:
+
* Операндов -- данные в кэше считаются актуальными в течение 5 секунд после создания, далее -- проверка по штампу времени.
* Настроек ролевой модели -- актуальность данных в кэше проверяется раз в 15 секунд.
* Хранимых процедур.
* Информации о карточках -- данные в кэше считаются актуальными в течение `60` секунд после создания, далее -- проверка по штампу времени.
* Результаты вычисления прав пользователя по ролевой модели.

== Клиентский кэш

Кэш данных на диске::
Используется для хранения данных файлов и строк секций карточек. Позволяет ускорить работу с данными карточек и справочников, которые уже были получены с сервера {dv}.
+
Расположение папки кэша управляется параметром `string`: `{hklm-dv}\Platform\5.5\ObjectManager\CachePath`. Кэш текущего пользователя и текущей БД по умолчанию размещается в папке `%TEMP%\DVCache\Имя БД\User ID`.
+
Типы кэшируемых данных определяются с помощью параметра `dword`: `HKEY_CURRENT_USER\SOFTWARE\Wow6432Node\DocsVision\Platform\5.5\ObjectManager\CacheMode`: `1` -- только карточки, `2` -- только файлы, `4` -- только справочники. Значение можно комбинировать: `3` (`1+2`) -- карточки и файлы.
+
Размер кэша не ограничен.
+
****
.Если клиент установлен в профиль пользователя, используйте следующие ветки реестра:
* `{hklm-dv}\Platform\5.5\ObjectManager\CachePath`.
* `HKEY_CURRENT_USER\SOFTWARE\Wow6432Node\DocsVision\Platform\5.5\ObjectManager\CacheMode`.
****

Кэш созданных экземпляров CardData::
Используется для хранения экземпляров класса `CardData` с данными карточки. Позволяет ускорить работу с данными карточек.
+
Размер кэша регулируется параметром `{hklm-dv}\Platform\5.5\Server\CardPoolSize` (по умолчанию -- `30` карточек). При превышении установленного размера кэша, из него удаляются `CardData` с данными карточек, но не справочников.

Кэш метаданных::
Используется для хранения информации о библиотеке карточек и о типах карточек. Данные являются статичными -- обновление выполняется при создании сессии.

Кэш UI-компонент карточек и справочников::
Используется для хранения экземпляров UI-компонент карточек и справочников. Позволяет ускорить открытие карточки. Данный кэш используется только в {wincl}е (не в РМА).
+
Управление кэшированием UI-компонента осуществляется с помощью программного интерфейса `IReusableCardComponent` -- позволяет разрешить или запретить кэширование.
+
Кэширование не работает для следующих UI-компонент: компоненты `VB6`, открытые в модальном режиме; карточки с `WPF` элементами управления (кэширование может быть включено через интерфейс `IReusableCardComponent`).
+
Карточки, открытые модально и не модально, кэшируются раздельно.
+
Размер кэша ограничен -- `20` экземпляров UI-компонент для одного типа карточек. Также кэш автоматически очищается при превышении клиентом лимита использования `User` и `GDI` объектов -- не более `7000`.

Информацию о кэшировании в {wc}е см. в xref:webclient:admin:caching-params.adoc[документации] для модуля {wc}.
