= Таблицы БД {dv}

.Далее приведено описание основных таблиц БД {dv}.
* *dvsys_binaries* -- информация о бинарных данных файлов, загруженных в {dv}.
* *dvsys_binary_storage_group_storages* -- группы хранилищ бинарных данных файлов.
* *dvsys_binary_storage_groups* -- информация о группах хранилищ.
* *dvsys_binary_storage_rules* -- правила помещения в хранилище.
* *dvsys_binary_storages* -- основные параметры внешних хранилищ: название, максимальный размер, состояние, разделы.
+
Настройки, устанавливаемые в разделе _Свойства_ конфигурации внешнего хранилища, хранятся в таблице *dvsys_objects*.
+
* *dvsys_cache_records* -- данные кэша поисковых запросов и представлений.
* *dvsys_carddefs* -- информация о типах карточек, загруженных в БД.
[#dvsys_carddefs_extensions]
* *dvsys_carddefs_extensions* -- информация о расширениях типов карточек.
+
В данной таблице содержится схема добавления расширенных метаданных в тип карточки, включая метаданные, добавленные с использованием Конструктора разметок.
+
* *dvsys_change_subscription_timestamps*, *dvsys_change_subscriptions*, *dvsys_change_subscriptions_cardtype* -- параметры подписок на события изменения карточек.
* *dvsys_crypto* -- криптообъекты (ключи подписи и шифрования), сформированные для карточек и файлов.
* *dvsys_dynamic_** -- данные динамических полей.
+
NOTE: Поддержка пользовательских метаданных, реализованная с использованием динамических метаданных, является устаревшей, текущая реализация -- расширенные метаданные.
+
* *dvsys_features* -- учёт использования подключений из дополнительных опций лицензии.
* *dvsys_fielddefs* -- информация о полях типов карточек, загруженных в БД.
* *dvsys_files* -- содержит атрибуты загруженных файлов: название, дата создания и редактирования, штамп времени и другие.
+
Также содержит ссылку *dvsys_files.BinaryID* на бинарные данные файлов.
+
* *dvsys_files_changed_binaries* -- информация об изменениях бинарных данных файлов.
* *dvsys_globalinfo* -- информация о базе данных {dv}: версия, состояние доступности БП, состояние доступности полнотекстового поиска и прочее.
* *dvsys_installers* -- информация о пакетах установки клиентских компонентов установленных модулей.
* *dvsys_instances* -- информация об экземплярах карточек:
+
** `InstanceID` -- идентификатор карточки.
** `CardTypeID` -- идентификатор типа карточки.
** `Description` -- дайджест.
** `SDID` -- ссылка на дескриптор безопасности в *dvsys_security*.
** `Deleted` -- карточка перемещена в корзину.
** `Template` -- карточка является шаблоном) и д.
+
Данные карточек (а точнее данные полей карточек) хранятся в таблицах *dvtable_Идентификатор*.
+
* *dvsys_instances_changed* -- список изменённых карточек, используемый при работе подсистемы подписок.
+
Периодически очищается задачей *dvjob_БД_purge_subscriptions*.
+
* *dvsys_instances_date* -- даты создания и последнего изменения карточек.
* *dvsys_instances_deleted* -- информация об окончательно удалённых карточках: идентификатор, дата удаления.
* *dvsys_instances_labels* -- цветовые метки карточек.
* *dvsys_instances_last_date* -- дата последнего изменения любой из карточек в БД.
* *dvsys_instances_read* -- список прочитанных пользователем карточек. Используется для установки признака "прочитанности" карточки.
* *dvsys_keyset_cursor_info* -- информация об открытых курсорах на keyset-таблицы: список идентификаторов карточек для отображения в представлении.
* *dvsys_keyset_sortings* -- информация о сортировке данных представления.
* *dvsys_keyset_tables* -- информация о keyset-таблицах.
* *dvsys_labels* -- список цветовых меток.
* *dvsys_libraries* -- информация о загруженных в БД библиотеках карточек: версия, схема и прочее.
* *dvsys_libraries_extensions* -- информация об установленных расширениях библиотек карточек. Расширения библиотек могут добавлять новые метаданные, см. *<<dvsys_carddefs_extensions,dvsys_carddefs_extensions>>*.
+
** *dvsys_links* -- информация о ссылке на карточки:
** `SourceCardID` -- идентификатор карточки, которая ссылается.
** `DestinationCardID` -- идентификатор карточки, на которую ссылаются.
** `Type` -- тип ссылки: 1 (слабая), 2 (сильная).
+
* *dvsys_locks* -- информация о действующих блокировках карточек или строк:
+
** `ResourceID` -- идентификатор заблокированной карточки или строки.
** `LockOwnerID` -- идентификатор пользователя-владельца блокировки.
** `SessionID` -- идентификатор пользовательской сессии для временной блокировки, `NULL` -- для постоянной.
** `SectionTypeID` -- идентификатор секции, `InstanceID` -- идентификатор карточки. Указываются, если заблокирована строка карточки.
+
* *dvsys_log* -- журналы работы системы.
* *dvsys_objects* -- дополнительные настройки подсистемы внешних хранилищ. В частности указываются пути для сохранения файлов для хранилищ на ФС.
* *dvsys_queue_** -- данные очереди обработки отложенных операций с бинарными данными файлов:
* *dvsys_queue_queue* -- перечень зарегистрированных очередей обработки.
* *dvsys_queue_object* -- список объектов, для которых должна быть выполнена отложенная операция:
+
** `QueueID` -- идентификатор очереди обработки.
** `ObjectID` -- идентификатор файла, бинарные данные которого обрабатываются.
+
* *dvsys_reports* -- перечень зарегистрированных _отчётов_. Реализация отчёта в хранимой процедуре *dvreport_get_data_ИД-процедуры*.
* *dvsys_search_results* -- список результатов поисковых запросов:
+
** `ParentID` -- идентификатор папки, в которой отображается результат запроса.
+
* *dvsys_search_results_data_ИД-запроса* -- результаты поискового запроса. Содержит идентификаторы найденных карточек.
* *dvsys_sectiondefs* -- информация о секциях карточек, загруженных в БД.
* *dvsys_security* -- дескрипторы безопасности объектов {dv}:
+
** `ID` -- идентификатор дескриптора.
** `SecurityDesc` -- дескриптор в закодированном виде.
+
* *dvsys_session_files*, *dvsys_session_icons,* *dvsys_session_objects* -- временные сессионные объекты.
* *dvsys_sessions* -- данные пользовательских сессий:
+
** `SessionID` -- идентификатор пользовательской сессии.
** `UserID` -- идентификатор пользователя.
** `LoginTime` -- дата и время подключения.
** `LastAccessTime` -- дата и время последнего действия.
** `Offline` -- признак офлайн сессии. Сессия, переключенная клиентом в офлайн режиме, не путать с неактивными сессиями.
+
NOTE: Сессия поддерживается в активном состоянии периодическим вызовом процедуры *session_touch*.
+
* *dvtable_Идентификатор* -- данные секции с идентификатором, указанным внутри фигурных скобок. В таблице хранятся стандартные и расширенные данные. Расширенные данные добавляются с помощью Конструктора разметок.

.В БД могут присутствовать таблицы с оригинальными именами с дополнительными постфиксами:
* *_archive* -- данные карточек и файлов, перемещенных в архив.
* *_userdependent* -- данные секций с зависимостью от пользователя. Если в настройках поля секции установлен флаг `*Зависит от пользователя*`.
* *_extended_old_data* и *_extended_archive_old_data* -- резервные копии таблиц расширенных секций оперативных и архивных карточек, полученные при обновлении модуля {pl} до версии 5.5.2. Для БД PostgreSQL данные таблицы будут иметь названия *_ext_old_data* и *_ext_arc_old_data*.
