= Обновление базы данных

При установке новой версии модуля в БД вносятся изменения. Масштаб обновления БД зависит от изменений в схеме карточек относительно текущего состояния в БД:

* Если изменилась версия генератора схем карточек.
+
** Будет выполнено полное обновление БД.
+
* Если изменилась схема библиотеки карточек, но не её карточек.
+
** Будут установлены или обновлены только расширенные отчёты и скрипты данной библиотеки карточек.
+
* Если изменилась схема карточки в библиотеке карточек:
+
** Библиотека карточек будет обновлена полностью.
+
** Будут загружены отчёты и скрипты библиотеки карточек, а также схемы всех карточек.
+
* Если изменений генератора, схемы библиотеки карточек и схем карточек не было:
+
** Обновление будет выполнено в лёгком режиме. Лёгкий режим обновления подразумевает только обновление версии компонентов библиотеки карточек в БД.

Обновление версии компонентов библиотеки карточек в БД выполняется во всех перечисленных случаях. Это требуется для работы механизма автоматического обновления клиентских компонентов в {wincl}е.
