= Перечень эксплуатационной документации

Каждый модуль {dv} сопровождается комплектом технической документации.

.Данный комплект может включать следующие документы:
* _Руководство администратора_ -- содержит программные и аппаратные требования модуля, инструкцию по установке и первоначальной настройке, требования к лицензии {dv}.
+
В зависимости от способа разграничения прав пользователей при работе с модулем, документ также может содержать инструкцию по настройке системы {dv} с помощью функций модуля и другую информацию.
+
* _Руководство пользователя_ -- содержит инструкцию по работе с функциями модуля. Также может содержать описание основных объектов модуля (карточек) и инструкцию по установке дополнительных компонентов пользовательского уровня.
* _Руководство программиста_ -- содержит описание программных объектов и функций API модуля, а также инструкцию по разработке компонентов модуля.
* _Описание конструкторов и справочников_ -- содержит описание пользовательского интерфейса и инструкцию по работе с конструкторами и справочниками, которые добавляются модулем в Систему.
* Другие документы и инструкции по модулю.

Также документация ДоксВижн содержит общие документы, относящиеся к нескольким модулям и всей Системе в целом.

.Актуальный список документов:
Общая документация::
* _Общее описание системы_ -- настоящий документ, в котором приведено описание компонентов Системы и взаимосвязей между ними: особенности лицензирования, оказания технической поддержки, перечень эксплуатационной документации.
* _Инструкция по установке системы {dv}_ -- содержит общие программные и аппаратные требования модулей {dv}, инструкцию по установке базовых модулей {dv} и первоначальной настройке Системы.
+
В данный документ включены отдельные пункты из руководств администратора базовых модулей {dv}. За более подробной инструкцией следует обращаться к руководству администратора соответствующего модуля.
+
* _Руководство программиста_ -- содержит описание API, которое предоставляется базовыми модулями {dv}, инструкции и примеры реализации различных компонентов системы {dv}. В данном документе не рассматриваются аспекты разработки, связанные с {wc}ом -- обратитесь к документации модуля _{wc}_.
* _Руководство по настройке_ -- содержит полное руководство по настройке поисковых запросов и представлений, информацию по настройке разметок, а также других не системных компонентов {dv}. Отдельные разделы документа отсылают в другим руководствам {dv}, в которых содержится описание требуемой настройки.
* _Описание полей стандартных карточек {dv}_ -- содержит описание карточек базовых модулей {dv}. Описание включает перечень метаданных с типами и значениями.
* _Инструкция по обновлению {dv} 5.5.X до 5.5.Y_ -- содержит инструкцию по установке комплекта новых версий модулей {dv}.

Документация базовых модулей::
Модуль {pl}:::
* _Руководство администратора_ -- содержит программные и аппаратные требования модуля, инструкцию по установке и настройке сервера {dv}. Также в документе приведена инструкция по управлению базами данных {dv}, настройке внешних файловых хранилищ, полнотекстового поиска и других параметров Системы, приведены рекомендации по обслуживанию.
* _Описание конструкторов и справочников_ -- содержит описание пользовательского интерфейса и инструкцию по работе со справочниками модуля: _Системные настройки_, _Справочник типов папок_, _Справочник компонентов_.
* _Ограничения на модификацию стандартных настроек модуля_ -- содержит перечень возможных и запрещенных изменений настроек и объектов модуля.

Модуль Базовые объекты:::
* _Руководство администратора_ -- содержит программные и аппаратные требования модуля, инструкцию по установке модуля, настройке маршрутизации заданий в электронную почту. Также в документе приведено описание настроек модуля в справочнике _Системные настройки_.
* _Руководство пользователя_ -- содержит описание карточки _Бизнес-календарь_, инструкцию по выполнению заданий в почтовом клиенте.
* _Описание конструкторов и справочников_ -- содержит описание пользовательского интерфейса и инструкцию по работе с конструкторами и справочниками модуля: _Конструктор правил нумерации_, _Конструктор разметок_, _Конструктор ролей_, _Конструктор скриптов_, _Конструктор состояний_, _Конструктор справочников_, _Справочник видов карточек_, _Справочник категорий_, _Справочник контрагентов_, _Справочник меток подписей_, _Справочник серверов_, _Справочник сотрудников_, _Справочник ссылок_.
* _Ограничения на модификацию стандартных настроек модуля_ -- содержит перечень возможных и запрещенных изменений настроек и объектов модуля.

Модуль Управление процессами:::
* _Руководство администратора_ -- содержит программные и аппаратные требования модуля, инструкцию по установке и настройке модуля. Также в документе содержится описание настроек модуля в _Консоли настройки {dv}_ и в справочнике _Системные настройки_, указаны особенности настройки кластера СУБП.
* _Руководство пользователя_ -- содержит описание Конструктора бизнес-процессов (инструмента для разработки БП); инструкцию по разработке новых бизнес-процессов; описание элементов, используемых при конструировании БП.

Приложение {ud}:::
* _Руководство администратора_ -- содержит требования, инструкцию по установке и настройке приложения, перечислены этапы подготовки приложения к работе с договорами.
* _Руководство пользователя_ -- содержит описание карточек модуля (*Документ УД*, _Задание УД_ и _Группа заданий УД_); рассмотренные основные примеры работы с документами, заданиями и договорами.
* _Ограничения на модификацию стандартных настроек приложения_ -- содержит перечень возможных и запрещенных изменений настроек и объектов приложения.

Модуль {ad}:::
* _Руководство администратора_ -- содержит программные и аппаратные требования модуля, инструкцию по установке модуля. Также в документе приведена инструкция по разработке процессов согласования.
* _Руководство пользователя_ -- содержит инструкцию по выполнению и контролю за выполнением задач согласования: согласование, консолидация и подписание.
* _Ограничения на модификацию стандартных настроек модуля_ -- содержит перечень возможных и запрещенных изменений настроек и объектов модуля.

Модуль {wincl}:::
* _Руководство администратора_ -- содержит программные и аппаратные требования модуля, инструкцию по установке, описание административных настроек.
* _Руководство пользователя_ -- содержит описание пользовательского интерфейса и инструкцию по работе с программами _{wincl}_ и _Рабочее место администратора_.

Приложение Делопроизводство 4.5:::
* _Руководство администратора_ -- содержит программные и аппаратные требования приложения, инструкцию по установке приложения _Делопроизводство 4.5_, приведено описание настроек приложения в справочнике _Системные настройки_.
* _Руководство пользователя_ -- содержит инструкцию по работе с программой _Личный помощник_. Описание карточек библиотеки карточек _Делопроизводство 4.5_ и инструкция по работе с карточками приведены в руководстве пользователя системы _{dv} 4.5_.