= Перечень эксплуатационной документации

Каждый модуль {dv} сопровождается комплектом технической документации.

.Данный комплект может включать следующие разделы:
* _Общая документация_ -- содержит программные и аппаратные требования модуля, описание структуры и функций модуля, требования к лицензии {dv}.
* _Администрирование модуля_ -- инструкцию по установке и первоначальной настройке, инструкцию по обновлению модуля, функции администратора.
+
В зависимости от способа разграничения прав пользователей при работе с модулем, документация также может содержать инструкцию по настройке системы {dv} с помощью функций модуля и другую информацию.
+
* _Руководство пользователя_ -- содержит инструкцию по работе с функциями модуля. Также может содержать описание основных объектов модуля (карточек) и инструкцию по установке дополнительных компонентов пользовательского уровня.
* _Руководство разработчика_ -- содержит описание программных объектов и функций API модуля, а также инструкцию по разработке компонентов модуля.
* _Описание конструкторов и справочников_ -- содержит описание пользовательского интерфейса и инструкцию по работе с конструкторами и справочниками, которые добавляются модулем в Систему.
* Изменения в релизной версии -- содержит список изменений, перечисление исправленных ошибок в текущей "релизной" версии, описание ошибок, исправленных в сборках технической поддержки после релиза.
* Другие документы и инструкции по модулю.

Также документация {dv} содержит общие документы, относящиеся к нескольким модулям и всей Системе в целом.

== Актуальный список документов

=== Общая документация

* _Общее описание системы_ -- настоящий документ, в котором приведено описание компонентов Системы и взаимосвязей между ними: особенности лицензирования, оказания технической поддержки, перечень эксплуатационной документации.
* _Инструкция по установке системы {dv}_ -- содержит общие программные и аппаратные требования модулей {dv}, инструкцию по установке базовых модулей {dv} и первоначальной настройке Системы.
+
В данный документ включены отдельные пункты из документации по администрированию базовых модулей {dv}. За более подробной инструкцией следует обращаться к руководству администратора соответствующего модуля.
+
* _Руководство разработчика_ -- содержит описание API, которое предоставляется базовыми модулями {dv}, инструкции и примеры реализации различных компонентов системы {dv}. В данном документе не рассматриваются аспекты разработки, связанные с {wc}ом -- обратитесь к документации модуля _{wc}_.
* _Руководство по настройке_ -- содержит полное руководство по настройке поисковых запросов и представлений, информацию по настройке разметок, а также других не системных компонентов {dv}. Отдельные разделы документа отсылают к другим руководствам {dv}, в которых содержится описание требуемой настройки.
* _Описание полей стандартных карточек {dv}_ -- содержит описание карточек базовых модулей {dv}. Описание включает перечень метаданных с типами и значениями.
* _Инструкция по обновлению {dv}_ -- содержит инструкцию по установке комплекта новых версий модулей {dv}.
* _Описание конструкторов и справочников_ -- содержит описание пользовательского интерфейса и инструкцию по работе со справочниками: _Системные настройки_, _Справочник типов карточек_, _Спрвочник компонентов_.

=== Документация модулей

==== Модуль {pl}

* _Общая документация_ -- содержит программные, аппаратные  и прочие требования модуля.
* _Администрирование модуля_ -- содержит инструкцию по установке и настройке сервера {dv}, инструкцию по обновлению модуля. Также в разделе приведена инструкция по управлению базами данных {dv}, настройке внешних файловых хранилищ, полнотекстового поиска и других параметров Системы, приведены рекомендации по обслуживанию.
* _Ограничения на изменение стандартных настроек модуля_ -- содержит перечень возможных и запрещённых изменений настроек и объектов модуля.
* Изменения в релизной версии -- содержит список изменений, перечисление исправленных ошибок в текущей "релизной" версии, описание ошибок, исправленных в сборках технической поддержки после релиза.

==== Модуль Служба {ws}

* _Общая документация_ -- содержит требования к модулю.
* _Администрирование модуля_ -- содержит инструкцию по установке и настройке Службы {ws}, инструкцию по обновлению модуля.
* Изменения в релизной версии -- содержит список изменений, перечисление исправленных ошибок в текущей "релизной" версии, описание ошибок, исправленных в сборках технической поддержки после релиза.

==== Модуль {bo}

* _Общая документация_ -- содержит программные и аппаратные требования модуля, описание функций.
* _Администрирование модуля_ -- содержит инструкцию по установке модуля, инструкцию по обновлению модуля, настройке маршрутизации заданий в электронную почту. Также в разделе приведено описание настроек модуля в справочнике _Системные настройки_.
* _Руководство пользователя_ -- содержит описание карточки _Бизнес-календарь_, инструкцию по выполнению заданий в почтовом клиенте.
* _Описание конструкторов и справочников_ -- содержит описание пользовательского интерфейса и инструкцию по работе с конструкторами и справочниками модуля: _Конструктор правил нумерации_, _Конструктор разметок_, _Конструктор ролей_, _Конструктор скриптов_, _Конструктор состояний_, _Конструктор справочников_, _Справочник видов карточек_, _Справочник категорий_, _Справочник контрагентов_, _Справочник меток подписей_, _Справочник серверов_, _Справочник сотрудников_, _Справочник ссылок_.
* _Ограничения на изменение стандартных настроек модуля_ -- содержит перечень возможных и запрещённых изменений настроек и объектов модуля.
* Изменения в релизной версии -- содержит список изменений, перечисление исправленных ошибок в текущей "релизной" версии, описание ошибок, исправленных в сборках технической поддержки после релиза.

==== Модуль {wf}

* _Общая документация_ -- содержит программные и аппаратные требования модуля, описание функций.
* _Администрирование модуля_ -- содержит инструкцию по установке и настройке модуля, инструкцию по обновлению модуля. Также в разделе содержится описание настроек модуля в _Консоли настройки {dv}_ и в справочнике _Системные настройки_, указаны особенности настройки кластера СУБП.
* _Руководство пользователя_ -- содержит описание Конструктора бизнес-процессов (инструмента для разработки БП); инструкцию по разработке новых бизнес-процессов; описание элементов, используемых при конструировании БП.
* Изменения в релизной версии -- содержит список изменений, перечисление исправленных ошибок в текущей "релизной" версии, описание ошибок, исправленных в сборках технической поддержки после релиза.

==== Приложение {dm}

* _Общая документация_ -- содержит программные и аппаратные требования модуля, описание функций.
* _Администрирование модуля_ -- содержит инструкцию по установке и настройке приложения, инструкцию по обновлению модуля, перечислены этапы подготовки приложения к работе с договорами.
* _Руководство пользователя_ -- содержит описание карточек модуля (_Документ УД_, _Задание УД_ и _Группа заданий УД_); рассмотрение основных примеров работы с документами, заданиями и договорами.
* _Ограничения на изменение стандартных настроек приложения_ -- содержит перечень возможных и запрещённых изменений настроек и объектов приложения.
* Изменения в релизной версии -- содержит список изменений, перечисление исправленных ошибок в текущей "релизной" версии, описание ошибок, исправленных в сборках технической поддержки после релиза.

==== Модуль {ad}

* _Общая документация_ -- содержит программные и аппаратные требования модуля, описание функций.
* _Администрирование модуля_ -- содержит инструкцию по установке модуля, инструкцию по обновлению модуля. Также в разделе приведена инструкция по разработке процессов согласования.
* _Руководство пользователя_ -- содержит инструкцию по выполнению и контролю за выполнением задач согласования: согласование, консолидация и подписание.
* _Ограничения на модификацию стандартных настроек модуля_ -- содержит перечень возможных и запрещённых изменений настроек и объектов модуля.
* Изменения в релизной версии -- содержит список изменений, перечисление исправленных ошибок в текущей "релизной" версии, описание ошибок, исправленных в сборках технической поддержки после релиза.

==== Модуль {wincl}

* _Общая документация_ -- содержит программные и аппаратные требования модуля, описание функций.
* _Администрирование модуля_ -- содержит инструкцию по установке модуля, инструкцию по обновлению модуля, описание административных настроек.
* _Руководство пользователя_ -- содержит описание пользовательского интерфейса и инструкцию по работе с программами _{wincl}_ и _Рабочее место администратора_.
* Изменения в релизной версии -- содержит список изменений, перечисление исправленных ошибок в текущей "релизной" версии, описание ошибок, исправленных в сборках технической поддержки после релиза.

==== Приложение {to}

* _Общая документация_ -- содержит программные и аппаратные требования модуля, описание функций.
* _Администрирование модуля_ -- содержит инструкцию по установке приложения _{to}_, инструкцию по обновлению, приведено описание настроек приложения в справочнике _Системные настройки_.
* _Руководство пользователя_ -- содержит инструкцию по работе с программой _Личный помощник_. Описание карточек библиотеки карточек _{to}_ и инструкция по работе с карточками приведены в руководстве пользователя системы _{dv} 4.5_.
* Изменения в релизной версии -- содержит список изменений, перечисление исправленных ошибок в текущей "релизной" версии, описание ошибок, исправленных в сборках технической поддержки после релиза.
