= Лицензирование функций системы

Для работы с системой {dv} требуется лицензия.

.Лицензия {dv} содержит два раздела:
. Основные параметры.
+
[subs=attributes]
----
{dv} Sample
Имя пользователя: {dv}
Дата генерации ключа: 23 июля 2019 г.
Редакция: Ecm
Максимальное количество соединений: 10
Возможность обновления до: 23 июля 2020 г.
Серийный номер: 1234-ABCD-1234-ABCD-1234-ABCD
Успешно активирована.
----
+
.Наиболее важные пункты:
****
Максимальное количество соединений::
Определяет максимальное количество клиентских подключений к серверу {dv}.
+
_Клиентское подключение_ -- подключение к серверу {dv} клиента с уникальной совокупностью имени пользователя и имени клиентского компьютера. Подключения, открытые с одного компьютера, но под разными пользователями, или с разных компьютеров под одной учётной записью считаются разными клиентскими подключениями. Подключения сервисов (например, СУБП) к серверу {dv} также считаются _клиентскими подключениями_.

Возможность обновления до::
Срок, в течении которого возможно получение обновлений и технической поддержки системы и модулей {dv}.
****
+
. Дополнительные опции.
+
Некоторые модули/приложения и функции системы {dv} являются лицензируемыми -- для их использования требуется наличие специальной опции в лицензии. Перечень данных разрешающих опций приведен в разделе _Дополнительные опции_ лицензии.
+
[subs=attributes]
----
Дополнительные опции:
{dv} Windows-Client
{dv} Personal (VIP) Licenses
Максимальное количество соединений: 12
{dv} Contracts
Максимальное количество соединений: 5
{dv} Внешнее хранилище ФС
{dv} Внешние файловые хранилища
----
+
Отдельные опции могут содержать параметр _Максимальное количество соединений_. Данный параметр определяет максимальное количество подключений, в которых будет действовать данная разрешающая опция.

== Конкурентные и персональные лицензии

Для подключения к серверу {dv} требуется лицензия на клиентское подключение. Лицензия может быть конкурентной -- пользователи конкурируют за получение лицензии из общего пула лицензий, или персональной -- закрепляемой за определённым пользователем.

Пользователю с персональной лицензией предоставляется право входа в {dv} даже когда все конкурентные лицензии используются. При этом персональная лицензия не даёт право приоритетного входа с нескольких рабочих мест -- подключиться с персональной лицензией при исчерпании пула конкурентных лицензий можно только с одного рабочего места.

Если для пользователя нет свободной лицензии (конкурентной или персональной) -- подключение к серверу {dv} будет запрещено.
