= Безопасность

В {dv} существует три модели безопасности: ролевая, дискреционная и мандатная. Модели безопасности регулируют доступ к объекту и разрешённые действия с ним.

Права на выполнение операций чтения, изменения, удаления объекта последовательно проверяются в строгом порядке по: мандатной, дискреционной, ролевой моделям безопасности. Если по какой-либо модели безопасности операция запрещена, по оставшимся проверка не производится.

.Дополнительные условия:
****
* Администраторам {dv} всегда предоставляются права на чтение (проверка не выполняется).
* Проверка по ролевой модели безопасности пропускается для следующих объектов:
- Объектов, которые не поддерживают ролевую модель. Например, папок.
- Карточек, настройки ролевой модели которых не предусматривают возможность запрета.
* Если в ролевой модели есть роли, устанавливающие запрет на операцию, сначала проверяются они. Если ролей, предусматривающих запрет, нет, права вычисляются по первой "разрешающей" роли.
****

[#role]
== Ролевая модель безопасности

Ролевая модель безопасности предусматривает разграничение прав доступа к объектам и операциям. Доступ будет разрешён или запрещён в зависимости от роли субъекта, работающего с объектами или операциями. Права доступа можно настроить с помощью матрицы доступа, содержащей перечень разрешенных и явно запрещенных операций для _роли_ в зависимости от типа операции и состояния объекта.

_Роль_ субъекта определяется системой {dv} по правилам включения в роль. Правила могут быть настроены с помощью предоставляемых условий или собственных хранимых процедур (SQL). В зависимости от правил, субъект может быть включен в несколько ролей.

Доступ к конкретной карточке по ролевой модели определяется настройками типа карточки, а также наличием или отсутствием в карточке системных данных о её виде и состоянии (секции `System`).

* Если системные данные обнаружены, анализируются настройки ролевой модели, определённые для вида. На основании данных настроек формируется дополнительный дескриптор, который объединяется с основным дескриптором карточки.
* Если системные данные в карточке отсутствуют, выполняется поиск родительской карточки, для которой определены настройки ролевой модели, и на их основании формируется дескриптор.
* Если будут найдены несколько родительских карточек с собственными настройками ролевой модели, дополнительный дескриптор будет построен на основании карточки, полученной из базы данных первой.
* Если родительские карточки не найдены, расчет доступа выполняется по собственному дескриптору карточки.

[#discrete]
== Дискреционная модель безопасности

В дискреционной модели безопасности управление доступом к объектам основано на списках управления доступом. В списках для каждой пары субъект-объект установлены типы доступа: чтение, изменение и другие. Каждый объект системы имеет привязанного к нему субъекта, называемого владельцем, и именно владелец устанавливает права доступа к объекту.

Дискреционная безопасность может быть настроена для карточек и справочников, папок, файлов, представлений, поисковых запросов, шаблонов выгрузки данных в Excel.

По умолчанию все пользователи {dv}, включенные в группу безопасности _{dv} Users_, получают полные права на все элементы системы.

При проверке прав сотрудника на объект учитываются права данного сотрудника, а также права его непосредственного подразделения, группы, роли. Начиная с выпуска версии модуля {pl} 5.5.2 может использоваться альтернативный режим проверки прав. Дополнительный режим учитывает не только права непосредственной организации, подразделения, группы, но и вышестоящих организаций и групп.

Если права на один объект выданы непосредственно сотруднику и его подразделению, роли, группе, приоритет имеют запрещающие права. Если права перетекают с контейнера к объекту, приоритет имеют права непосредственно выданные на объект. Например, если права переходят от папки к карточке, права карточки будут в приоритете.

[#mandate]
== Мандатная модель безопасности

Мандатная модель безопасности предусматривает наличие у объектов меток конфиденциальности содержащейся информации. Метки определяют уровень доступа. Субъекты же обладают допуском к объектам с определённым уровнем метки конфиденциальности.

В системе {dv} имеется пять уровней доступа и допуска: _самый низкий_, _низкий_, _средний_, _высокий_, _самый высокий_.

.Правила мандатной модели безопасности:
* Субъект имеет право читать и заносить информацию только в документы, уровень доступа которых ниже или равен уровню допуска субъекта.
* Автор документа самостоятельно может изменять уровень доступа к нему на более низкий, чем его уровень допуска.
+
TIP: Администратор безопасности -- пользователь, включенный в группу _{dv} Security Administrators_.
+
* Изменить уровень безопасности как субъекта, так и объекта может только администратор безопасности.
* Пользователи, включенные в группу безопасности _{dv} Administrators_ всегда имеют неизменяемый уровень допуска _высокий_.
* Пользователи, включенные в группу безопасности _{dv} Security Administrators_ всегда имеют неизменяемый уровень допуска _самый высокий_.
* Пользователь с любым уровнем допуска создает объекты с уровнем конфиденциальности _самый низкий_.
* В папке с любым уровнем доступа вложенная папка и карточка будут созданы с уровнем конфиденциальности _самый низкий_.
* Если к карточке с любым уровнем доступа прикладывается файл файловой системы, то создаваемая при этом карточка файла получит уровень конфиденциальности _самый низкий_.
* Если к карточке с любым уровнем доступа прикладывается уже существующая карточка файла, то она сохранит свой уровень доступа.
+
Например, пользователь с высоким уровнем допуска может приложить к карточке с низким уровнем доступа файл, имеющий высокий уровень доступа. В этом случае приложенный файл смогут увидеть только те пользователи, которым это позволяет их уровень допуска.
+
* Карточка, создаваемая из карточки с любым уровнем доступа, будет иметь уровень конфиденциальности _самый низкий_.
* Объект унаследует уровень доступа от родительского объекта, если они связаны сильной ссылкой вне зависимости от уровня конфиденциальности дочернего объекта.
